package devicons

var extensions = map[string]rune{
	"styl":         '',
	"sass":         '',
	"scss":         '',
	"htm":          '',
	"slim":         '',
	"ejs":          '',
	"css":          '',
	"less":         '',
	"md":           '',
	"mdx":          '',
	"markdown":     '',
	"rmd":          '',
	"json":         '',
	"js":           '',
	"mjs":          '',
	"jsx":          '',
	"rb":           '',
	"php":          '',
	"py":           '',
	"pyc":          '',
	"pyo":          '',
	"pyd":          '',
	"coffee":       '',
	"mustache":     '',
	"hbs":          '',
	"conf":         '',
	"ini":          '',
	"yml":          '',
	"yaml":         '',
	"toml":         '',
	"bat":          '',
	"jpg":          '',
	"jpeg":         '',
	"bmp":          '',
	"png":          '',
	"gif":          '',
	"ico":          '',
	"twig":         '',
	"cpp":          '',
	"c++":          '',
	"cxx":          '',
	"cc":           '',
	"cp":           '',
	"c":            '',
	"cs":           '',
	"h":            '',
	"hh":           '',
	"hpp":          '',
	"hxx":          '',
	"hs":           '',
	"lhs":          '',
	"lua":          '',
	"java":         '',
	"sh":           '',
	"fish":         '',
	"bash":         '',
	"zsh":          '',
	"ksh":          '',
	"csh":          '',
	"awk":          '',
	"ps1":          '',
	"ml":           'λ',
	"mli":          'λ',
	"diff":         '',
	"db":           '',
	"sql":          '',
	"dump":         '',
	"clj":          '',
	"cljc":         '',
	"cljs":         '',
	"edn":          '',
	"scala":        '',
	"go":           '',
	"dart":         '',
	"xul":          '',
	"sln":          '',
	"suo":          '',
	"pl":           '',
	"pm":           '',
	"t":            '',
	"rss":          '',
	"f#":           '',
	"fsscript":     '',
	"fsx":          '',
	"fs":           '',
	"fsi":          '',
	"rs":           '',
	"rlib":         '',
	"d":            '',
	"erl":          '',
	"hrl":          '',
	"ex":           '',
	"exs":          '',
	"eex":          '',
	"leex":         '',
	"vim":          '',
	"ai":           '',
	"psd":          '',
	"psb":          '',
	"ts":           '',
	"tsx":          '',
	"jl":           '',
	"pp":           '',
	"vue":          '﵂',
	"elm":          '',
	"swift":        '',
	"xcplayground": '',
}

var exactMatches = map[string]rune{
	"exact-match-case-sensitive-1.txt": '1',
	"exact-match-case-sensitive-2":     '2',
	"gruntfile.coffee":                 '',
	"gruntfile.js":                     '',
	"gruntfile.ls":                     '',
	"gulpfile.coffee":                  '',
	"gulpfile.js":                      '',
	"gulpfile.ls":                      '',
	"mix.lock":                         '',
	"dropbox":                          '',
	".ds_store":                        '',
	".gitconfig":                       '',
	".gitignore":                       '',
	".gitlab-ci.yml":                   '',
	".bashrc":                          '',
	".zshrc":                           '',
	".vimrc":                           '',
	".gvimrc":                          '',
	"_vimrc":                           '',
	"_gvimrc":                          '',
	".bashprofile":                     '',
	"favicon.ico":                      '',
	"license":                          '',
	"node_modules":                     '',
	"react.jsx":                        '',
	"procfile":                         '',
	"dockerfile":                       '',
	"docker-compose.yml":               '',
}

//
// let s:file_node_pattern_matches = {
//       \ '.*jquery.*\.js$'       : '',
//       \ '.*angular.*\.js$'      : '',
//       \ '.*backbone.*\.js$'     : '',
//       \ '.*require.*\.js$'      : '',
//       \ '.*materialize.*\.js$'  : '',
//       \ '.*materialize.*\.css$' : '',
//       \ '.*mootools.*\.js$'     : '',
//       \ '.*vimrc.*'             : '',
//       \ 'Vagrantfile$'          : ''
//       \}
